export {crearDeck} from './01-crear-deck.js'
export {pedirCarta} from './02-pedir-carta.js'
export {valorCarta} from './03-valor-carta.js'
export {turnoComputadora} from './04-turno-computadora.js'
export {crearCartaHTML} from './05-crear-carta.js'
export {determinarGanador} from './06-determinar-ganador.js'